# <center><div style="width: 370px;"> ![Panel Data](pictures/Panel_Data.jpg)

 # <center> Descriptive Statistics

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame(
    {
    "one": pd.Series(np.random.randn(3), index=list('abc')),
    "two": pd.Series(np.random.randn(4), index=list('abcd')),
    "three": pd.Series(np.random.randn(3), index=list('bcd'))
    }
)
    

In [3]:
df

one       two     three
a  0.417446  0.973601       NaN
b  0.475173  0.529538 -1.549041
c  0.718222 -1.061773 -0.987357
d       NaN -0.126139 -0.417280

In [4]:
df.mode()

one       two     three
0  0.417446 -1.061773 -1.549041
1  0.475173 -0.126139 -0.987357
2  0.718222  0.529538 -0.417280
3       NaN  0.973601       NaN

There exists a large number of methods for computing descriptive statistics and other related operations on Series, DataFrame. Most of these are aggregations (hence producing a lower-dimensional result) like `sum()`, `mean()`, and `quantile()`, but some of them, like `cumsum()` and `cumprod()`, produce an object of the same size. Generally speaking, these methods take an axis argument, just like ndarray.{sum, std, . . . }, but the axis can be specified by name or integer:

In [5]:
df.mean(axis=0)

one      0.536947
two      0.078807
three   -0.984559
dtype: float64

In [6]:
df.mean(0)

one      0.536947
two      0.078807
three   -0.984559
dtype: float64

In [7]:
# axis = 0 is equal to axis = 'rows'
df.mean(axis='rows')

one      0.536947
two      0.078807
three   -0.984559
dtype: float64

In [8]:
# 'index' is the same as 'rows' or 0
df.mean(axis='index')

one      0.536947
two      0.078807
three   -0.984559
dtype: float64

In [9]:
df.mean(axis=1)

a    0.695523
b   -0.181444
c   -0.443636
d   -0.271709
dtype: float64

In [10]:
df.sum(axis=1)

a    1.391047
b   -0.544331
c   -1.330908
d   -0.543419
dtype: float64

In [11]:
df.sum(1)

a    1.391047
b   -0.544331
c   -1.330908
d   -0.543419
dtype: float64

Combined with the broadcasting / arithmetic behavior, one can describe various statistical procedures, like standardization (rendering data zero mean and standard deviation of 1), very concisely:

In [12]:
df

one       two     three
a  0.417446  0.973601       NaN
b  0.475173  0.529538 -1.549041
c  0.718222 -1.061773 -0.987357
d       NaN -0.126139 -0.417280

In [13]:
ts_stand = (df - df.mean()) / df.std()

In [14]:
ts_stand.std()

one      1.0
two      1.0
three    1.0
dtype: float64

In [15]:
xs_stand = df.sub(df.mean(1), axis=0).div(df.std(1), axis=0)

In [16]:
xs_stand.std(1)

a    1.0
b    1.0
c    1.0
d    1.0
dtype: float64

> Note that methods like `cumsum()` and `cumprod()` preserve the location of NaN values.

In [18]:
abs(df).cumsum(axis=1)

one       two     three
a  0.417446  1.391047       NaN
b  0.475173  1.004710  2.553752
c  0.718222  1.779994  2.767351
d       NaN  0.126139  0.543419

Here is a quick reference summary table of common functions. Each also takes an
optional `level` parameter which applies only if the object has a
[hierarchical index](https://pandas.pydata.org/docs/user_guide/advanced.html#advanced-hierarchical).

|Function|Description|
|:--|:--|
|`count`|Number of non-NA observations|
|`sum`|Sum of values|
|`mean`|Mean of values|
|`mad`|Mean absolute deviation|
|`median`|Arithmetic median of values|
|`min`|Minimum|
|`max`|Maximum|
|`mode`|Mode|
|`abs`|Absolute Value|
|`prod`|Product of values|
|`std`|Bessel-corrected sample standard deviation|
|`var`|Unbiased variance|
|`sem`|Standard error of the mean|
|`skew`|Sample skewness (3rd moment)|
|`kurt`|Sample kurtosis (4th moment)|
|`quantile`|Sample quantile (value at %)|
|`cumsum`|Cumulative sum|
|`cumprod`|Cumulative product|
|`cummax`|Cumulative maximum|
|`cummin`|Cumulative minimum|

`Series.unique()` will return the number of unique non-NA values in a Series:

In [23]:
series = pd.Series(np.random.randn(500))

In [24]:
series.nunique()

500

In [26]:
series[5: 100] = np.nan

In [27]:
series[100: 500] = 100

In [28]:
series

0        1.450745
1       -0.686133
2        0.423568
3       -0.222795
4       -1.897097
          ...    
495    100.000000
496    100.000000
497    100.000000
498    100.000000
499    100.000000
Length: 500, dtype: float64

In [29]:
series.nunique()

6

In [30]:
# On a dataframe, nunique return number of unique values per column
df.nunique()

one      3
two      4
three    3
dtype: int64

## Summarizing data: describe

There is a convenient `describe()` function which computes a variety of summary statistics about a Series or the columns of a DataFrame (excluding NAs of course):

In [33]:
series = pd.Series(np.random.randn(1000))
series[::2] = np.nan

In [34]:
series

0           NaN
1     -0.887630
2           NaN
3      0.261227
4           NaN
         ...   
995    1.020218
996         NaN
997    0.228941
998         NaN
999    1.661472
Length: 1000, dtype: float64

In [35]:
series.describe()

count    500.000000
mean      -0.028347
std        0.986361
min       -2.672346
25%       -0.703065
50%       -0.074203
75%        0.623564
max        2.688249
dtype: float64

In [36]:
frame = pd.DataFrame(np.random.randn(1000, 5), columns=list('abcde'))

In [38]:
frame[::2] = np.nan

In [39]:
frame

a         b         c         d         e
0         NaN       NaN       NaN       NaN       NaN
1   -1.017469 -0.359021 -0.545455 -1.228823  0.262228
2         NaN       NaN       NaN       NaN       NaN
3   -0.288404 -0.039554 -1.295165 -1.648444  0.386424
4         NaN       NaN       NaN       NaN       NaN
..        ...       ...       ...       ...       ...
995  0.432696 -1.461108  0.012362  0.907570  0.999509
996       NaN       NaN       NaN       NaN       NaN
997  0.023167 -0.827143 -0.671728 -0.180859  1.676407
998       NaN       NaN       NaN       NaN       NaN
999  0.159510  1.061401  0.938039  0.946283  1.102525

[1000 rows x 5 columns]

In [40]:
frame.describe()

a           b           c           d           e
count  500.000000  500.000000  500.000000  500.000000  500.000000
mean    -0.058044   -0.016835   -0.012688   -0.025576    0.029938
std      0.990470    1.020516    0.945029    1.022486    0.969703
min     -2.816336   -2.725427   -3.372055   -3.353105   -3.387212
25%     -0.750222   -0.657493   -0.655080   -0.654074   -0.625903
50%      0.001106   -0.023048   -0.024434   -0.047740   -0.026310
75%      0.613630    0.653058    0.628059    0.650953    0.715267
max      2.989116    2.692466    2.934214    2.940461    3.067362

In [48]:
series.describe(percentiles=[0.05, 0.75, 0.95])

count    500.000000
mean      -0.028347
std        0.986361
min       -2.672346
5%        -1.599028
50%       -0.074203
75%        0.623564
95%        1.554062
max        2.688249
dtype: float64

**By default, the median (50% percentile) is always included.**

For a non-numerical Series object, `describe()` will give a simple summary of the number of unique values and most frequently occurring values:

In [49]:
s = pd.Series(["a", "a", "b", "b", "a", "a", np.nan, "c", "d", "a"])

In [51]:
s.describe()

count     9
unique    4
top       a
freq      5
dtype: object

Note that on a mixed-type DataFrame object, `describe()` will restrict the summary to include only numerical columns or, if none are, only categorical columns:

In [52]:
frame = pd.DataFrame(
    {"a": ["Yes", "Yes", "No", "No"], "b": range(4)}
)

In [53]:
frame.describe()

b
count  4.000000
mean   1.500000
std    1.290994
min    0.000000
25%    0.750000
50%    1.500000
75%    2.250000
max    3.000000

This behavior can be controlled by providing a list of types as `include`/`exclude` arguments. The special value `all` can also be used:

In [54]:
frame.describe(include=["object"])

a
count     4
unique    2
top     Yes
freq      2

In [55]:
frame.describe(include=["number"])

b
count  4.000000
mean   1.500000
std    1.290994
min    0.000000
25%    0.750000
50%    1.500000
75%    2.250000
max    3.000000

In [56]:
frame.describe(include="all")

a         b
count     4  4.000000
unique    2       NaN
top     Yes       NaN
freq      2       NaN
mean    NaN  1.500000
std     NaN  1.290994
min     NaN  0.000000
25%     NaN  0.750000
50%     NaN  1.500000
75%     NaN  2.250000
max     NaN  3.000000

That feature relies on `[select_dtypes]` which will be discussed later.

## Index of min/max values

The `idxmin()` and `idxmax()` functions on Series and DataFrame compute the index labels with the minimum and maximum corresponding values:

In [59]:
s1 = pd.Series(np.random.randn(5))

In [60]:
s1

0   -0.105719
1   -0.130703
2   -1.002470
3    0.095524
4   -0.904585
dtype: float64

In [63]:
s1.idxmax(), s1.idxmin()

(3, 2)

In [64]:
df1 = pd.DataFrame(np.random.randn(5, 3), columns=["A", "B", "C"])

In [65]:
df1

A         B         C
0 -0.864826 -0.986356 -1.120342
1 -0.052806  0.108048  0.429228
2 -1.985612  0.017062 -0.976114
3 -0.756991 -0.781669  0.713236
4  0.371859  0.574532  1.866772

In [68]:
df1.idxmin(axis=0)

A    2
B    0
C    0
dtype: int64

In [69]:
df1.idxmax(axis=0)

A    4
B    4
C    4
dtype: int64

When there are multiple rows (or columns) matching the minimum or maximum value, `idxmin()` and `idxmax()` return the first matching index:

In [70]:
df2 = pd.DataFrame(
    [2, 1, 1, 3, np.nan], columns=["A"], index=list("edcba"))

In [71]:
df2

A
e  2.0
d  1.0
c  1.0
b  3.0
a  NaN

In [72]:
df2["A"].idxmin()

'd'

> **Note:** `idxmin` and `idxmax` are called `argmin` and `argmax` in NumPy.

## Value counts (histogramming) / mode

The `value_counts()` Series method and top-level function computes a histogram of a 1D array of values. It can also be used as a function on regular arrays:

In [76]:
data = np.random.randint(1, 7, size=50)

In [77]:
data

array([1, 4, 1, 2, 2, 4, 5, 2, 5, 6, 1, 4, 3, 3, 2, 5, 3, 2, 6, 1, 3, 6,
       2, 3, 2, 6, 2, 2, 4, 4, 6, 4, 6, 2, 2, 4, 6, 3, 5, 4, 2, 3, 2, 2,
       4, 5, 5, 3, 1, 4])

In [78]:
s = pd.Series(data)

In [80]:
s.value_counts()

2    14
4    10
3     8
6     7
5     6
1     5
Name: count, dtype: int64

In [81]:
pd.value_counts(data)

/tmp/ipykernel_897/3657943749.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(data)


2    14
4    10
3     8
6     7
5     6
1     5
Name: count, dtype: int64

The `value_counts()` method can be used to count combinations across multiple columns. By default all columns are used but a subset can be selected using the `subset` argument.

In [82]:
data = {"a": [1, 2, 3, 4], "b": ['x', 'x', 'y', 'y']}

In [83]:
frame = pd.DataFrame(data)

In [84]:
frame

a  b
0  1  x
1  2  x
2  3  y
3  4  y

In [85]:
frame.value_counts()

a  b
1  x    1
2  x    1
3  y    1
4  y    1
Name: count, dtype: int64

Similarly, you can get the most frequently occurring value(s), i.e. the mode, of the values in a Series or DataFrame:

In [86]:
s3 = pd.Series([1, 1, 3, 3, 3, 5, 5, 7, 7, 7])

In [87]:
s3

0    1
1    1
2    3
3    3
4    3
5    5
6    5
7    7
8    7
9    7
dtype: int64

In [88]:
s3.mode()

0    3
1    7
dtype: int64

In [89]:
df3 = pd.DataFrame(
    {
        "A": np.random.randint(0, 7, size=50),
        "B": np.random.randint(-10, 15, size=50),
    }
)

In [90]:
df3.mode()

A    B
0  0  6.0
1  2  NaN

## Discretization and quantiling

Continuous values can be discretized using the `cut()` (bins based on values) and `qcut()` (bins based on sample quantiles) functions:

`pd.cut` has equal cuts by default:

In [91]:
pd.cut([1, 2, 3, 4], 3)

[(0.997, 2.0], (0.997, 2.0], (2.0, 3.0], (3.0, 4.0]]
Categories (3, interval[float64, right]): [(0.997, 2.0] < (2.0, 3.0] < (3.0, 4.0]]

and you can provide `labels` to replace the ranges:

In [92]:
pd.cut([1, 2, 3, 4], 3, labels=[1, 2, 3])

[1, 1, 2, 3]
Categories (3, int64): [1 < 2 < 3]

You can also customize the cut edges by proving an array of edges. Here we cut the array at -5, -1, 0, 1, 5 values:

In [94]:
arr = np.random.randn(20)
factor = pd.cut(arr, [-5, -1, 0, 1, 5])

In [95]:
factor

[(-5, -1], (0, 1], (-5, -1], (-1, 0], (0, 1], ..., (-1, 0], (1, 5], (-1, 0], (-1, 0], (1, 5]]
Length: 20
Categories (4, interval[int64, right]): [(-5, -1] < (-1, 0] < (0, 1] < (1, 5]]

`qcut()` computes sample quantiles. For example, we could slice up some normally distributed data into equal-size quartiles like so:

In [96]:
arr = np.random.randn(30)
arr

array([ 0.3053849 , -0.17041624, -1.59854311, -0.80816019,  2.531207  ,
       -0.07192321,  1.45694419, -1.48153015,  0.07719385, -0.17257442,
        0.19308549,  0.43044014,  0.05617508,  0.59775132,  0.15982602,
       -0.51228673, -0.52630464, -2.37605461, -1.47459582, -0.65992471,
       -0.20398006, -0.23136418,  0.32820632,  0.40084065,  0.68742381,
        0.60198351, -1.13249804,  1.05776786, -0.32400431,  1.56361047])

In [97]:
factor = pd.qcut(arr, [0, 0.25, 0.5, 0.75, 1], labels=range(4))

In [98]:
factor

[2, 1, 0, 0, 3, ..., 3, 0, 3, 1, 3]
Length: 30
Categories (4, int64): [0 < 1 < 2 < 3]

In [99]:
pd.value_counts(factor)

/tmp/ipykernel_897/524676245.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(factor)


0    8
3    8
1    7
2    7
Name: count, dtype: int64

We can also pass infinite values to define the bins:

In [100]:
arr = np.random.randn(20)

In [101]:
factor = pd.cut(arr, [-np.inf, 0, np.inf], labels=["-", "+"])

In [102]:
factor

['+', '-', '-', '+', '+', ..., '+', '-', '-', '+', '-']
Length: 20
Categories (2, object): ['-' < '+']

In [103]:
arr

array([ 0.05721335, -1.24636953, -0.73800218,  0.97778536,  0.45207106,
        0.12335759,  0.22184179,  0.26141949, -1.15353544,  0.03892081,
        0.18841391,  0.01708136, -0.48556434,  2.04403918, -0.17776896,
        0.87301977, -1.95191938, -0.54038328,  0.55796825, -0.51399947])

You can also have repetitive labels, but you have to set the `order` keyword argument to `False` as it doesn't make sense to define order with repitative values. Otherwise, you will get `ValueError`.

In [104]:
pd.cut(
    [-2, 0, 1, 2, 3, 4, 5, 6, 7],
    [0, 3, 6, 9],
    labels=["B", "A", "B"],
    ordered=False
)

[NaN, NaN, 'B', 'B', 'B', 'A', 'A', 'A', 'B']
Categories (2, object): ['A', 'B']

> Note that when you have values out of bins, `NaN` is returned.