# <center> <div style="width: 370px;"> ![numpy title](pictures/numpy_tytle.jpg)

# <center>Data Science Operations: Order, Aggregate

## Transposing, Sorting, and Concatenating

In [1]:
import numpy as np

Transposing in NumPy is a common operation that involves changing the shape of a NumPy array by flipping its rows and columns. You can think of it as rotating the data along its diagonal. NumPy provides the `.T` attribute for transposing arrays and the `numpy.transpose()` function for more complex transformations. Here's how you can perform transposing in NumPy:

For a 1-D array, this returns an unchanged view of the original array, as a transposed vector is simply the same vector. To convert a 1-D array into a 2-D column vector, an additional dimension must be added, e.g., `np.atleast2d(a).T` achieves this, as does `a[:, np.newaxis]`. For a 2-D array, this is the standard matrix transpose. For an n-D array, if axes are given, their order indicates how the axes are permuted (see Examples). If axes are not provided, then `transpose(a).shape == a.shape[::-1]`.


In [4]:
a = np.array(np.random.randint(10, size=(3, 4)))

In [5]:
a

array([[0, 6, 5, 8],
       [4, 5, 2, 2],
       [0, 7, 7, 2]])

In [6]:
a.T

array([[0, 4, 0],
       [6, 5, 7],
       [5, 2, 7],
       [8, 2, 2]])

In [7]:
a.transpose()

array([[0, 4, 0],
       [6, 5, 7],
       [5, 2, 7],
       [8, 2, 2]])

In [13]:
np.transpose(a, axes=None)

array([[0, 4, 0],
       [6, 5, 7],
       [5, 2, 7],
       [8, 2, 2]])

When you calculate the transpose of an array, the row and column indices of every element are switched. Item `[0, 2]`, for example, becomes item `[2, 0]`. You can also use `a.T` as an alias for `a.transpose()`.

The following code block shows sorting, but you’ll also see a more powerful sorting technique in the coming section on structured data:

In [21]:
data = np.array(np.random.randint(10, size=(3, 3)))
data

array([[8, 7, 7],
       [9, 8, 3],
       [4, 2, 9]])

Omitting the axis argument automatically selects the last and innermost dimension, which is the rows in this example. Using None flattens the array and performs a global sort. Otherwise, you can specify which axis you want. In output of `np.sort(data, axis=0)`, each column of the array still has all of its elements but they have been sorted low-to-high inside that column.


In [22]:
np.sort(data)

array([[7, 7, 8],
       [3, 8, 9],
       [2, 4, 9]])

In [23]:
np.sort(data, axis=None)

array([2, 3, 4, 7, 7, 8, 8, 9, 9])

In [24]:
np.sort(data, axis=0)

array([[4, 2, 3],
       [8, 7, 7],
       [9, 8, 9]])

In [25]:
np.sort(data, axis=1)

array([[7, 7, 8],
       [3, 8, 9],
       [2, 4, 9]])


Finally, here’s an example of concatenation. While there’s a `np.concatenate()` function, there are also a number of helper functions that are sometimes easier to read.

In [27]:
a = np.array(np.random.randint(10, size=(3, 4)))
b = np.array(np.random.randint(10, size=(3, 4)))

In [28]:
a

array([[7, 4, 2, 1],
       [7, 6, 6, 4],
       [6, 5, 2, 5]])

In [29]:
b

array([[9, 2, 1, 5],
       [6, 8, 5, 9],
       [8, 8, 6, 0]])

In [30]:
np.hstack((a, b))

array([[7, 4, 2, 1, 9, 2, 1, 5],
       [7, 6, 6, 4, 6, 8, 5, 9],
       [6, 5, 2, 5, 8, 8, 6, 0]])

In [31]:
np.vstack((a, b))

array([[7, 4, 2, 1],
       [7, 6, 6, 4],
       [6, 5, 2, 5],
       [9, 2, 1, 5],
       [6, 8, 5, 9],
       [8, 8, 6, 0]])

In [32]:
np.concatenate((a, b))

array([[7, 4, 2, 1],
       [7, 6, 6, 4],
       [6, 5, 2, 5],
       [9, 2, 1, 5],
       [6, 8, 5, 9],
       [8, 8, 6, 0]])

In [33]:
np.concatenate((a, b), axis=0)

array([[7, 4, 2, 1],
       [7, 6, 6, 4],
       [6, 5, 2, 5],
       [9, 2, 1, 5],
       [6, 8, 5, 9],
       [8, 8, 6, 0]])

In [34]:
np.concatenate((a, b), axis=1)

array([[7, 4, 2, 1, 9, 2, 1, 5],
       [7, 6, 6, 4, 6, 8, 5, 9],
       [6, 5, 2, 5, 8, 8, 6, 0]])

In [35]:
np.concatenate((a, b), axis=None)

array([7, 4, 2, 1, 7, 6, 6, 4, 6, 5, 2, 5, 9, 2, 1, 5, 6, 8, 5, 9, 8, 8,
       6, 0])

The NumPy functions `np.hstack()` and `np.vstack()` concatenate arrays horizontally and vertically, respectively. The function `np.concatenate()` is more generic and can concatenate arrays along any axis. By default, `np.concatenate()` concatenates arrays along the first axis, but you can also specify a different axis using the `axis` argument.

One important thing to note is that all of these functions require the arrays to be passed in as a tuple. This is because the functions can concatenate any number of arrays, and a tuple is a convenient way to represent a sequence of objects.


## Aggregating


Before delving into more advanced topics and examples, let's explore the concept of aggregation in NumPy. During this journey through NumPy's functionality, you've already encountered several aggregation methods such as `.sum()`, `.max()`, `.mean()`, and `.std()`. NumPy offers a wide range of additional functions for aggregation purposes, covering mathematical, financial, and statistical domains. These aggregation functions play a crucial role in simplifying your data by reducing its dimensions, making complex data analysis tasks more manageable.

In [38]:
import numpy as np

In [62]:
data = np.array(np.random.randint(1000, 2000, size=10))

In [63]:
data

array([1015, 1290, 1204, 1240, 1063, 1894, 1007, 1588, 1119, 1133])

In [64]:
np.sum(data)

12553

In [65]:
np.max(data)

1894

In [66]:
np.mean(data)

1255.3

In [67]:
np.std(data)

266.947204518047