# <center> <div style="width: 370px;"> ![numpy title](pictures/numpy_tytle.jpg)

# <center>Exercise

The purpose of these exercises is to test the skills that have been learned so far in NumPy and to increase those skills

### Exercise 0.

What is Numpy?

NumPy, short for Numerical Python, stands as a remarkably versatile, meticulously optimized, open-source package dedicated to the realm of array processing. Within its extensive toolkit, NumPy equips users to harness top-tier performance when working with N-dimensional arrays, fostering a seamless experience in the world of numerical computing.

This robust library is not confined to a single domain; rather, it serves as a powerhouse for a multitude of tasks, including scientific computations, intricate mathematical operations, logical evaluations, sorting tasks, I/O functions, fundamental statistical analyses, and pivotal linear algebra manipulations. Moreover, NumPy doesn't stop there; it extends its utility to the realm of random simulations and broadcasting functionalities, offering a comprehensive suite of tools to cater to diverse computational needs.

The wealth of capabilities inherent to NumPy has earned it widespread acclaim and made it the preferred choice among developers and researchers alike. The visual representation below succinctly illustrates the versatile applications of NumPy, showcasing its indispensability in modern data science and scientific computing.

### Exersice 1.

 Import numpy as np and see the version

In [8]:
import numpy as np
np.__version__

'1.25.2'

### Exercise 2.

How to create a 1D array?

In [32]:
a = np.array(np.arange(100))

In [33]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

### Exercise 3.

How to create a boolean array?

In [46]:
a = np.array(np.random.randint(0, 2, size=10), dtype=bool)
a

array([False, False,  True,  True,  True, False, False,  True, False,
       False])

In [60]:
a = np.full((2, 2, 3), (True, False, False), dtype=bool)

In [61]:
a

array([[[ True, False, False],
        [ True, False, False]],

       [[ True, False, False],
        [ True, False, False]]])

### Exercise 4.

Create a null vector of size 10 

In [63]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Exercise 5.

How to find the memory size of any array 

In [67]:
a.size * a.itemsize

80

### Exercise 6.

make zeros array with 10 elements, that $5^{th}$ element equal 1.

In [87]:
a = np.zeros(10, dtype=int)
a[4] = 1
a

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

### Exercise 7.

Given are 2 similar dimensional numpy arrays, how to get a numpy array output in which every element is an element-wise sum of the 2 numpy arrays.

In [94]:
a = np.array(np.random.randint(0, 10, size=(2, 3)))
b = np.array(np.random.randint(0, 10, size=(2, 3)))
a, b

(array([[9, 9, 4],
        [0, 7, 8]]),
 array([[4, 9, 4],
        [3, 8, 9]]))

In [95]:
a + b

array([[13, 18,  8],
       [ 3, 15, 17]])

### Exercise 8.

Given a numpy array (matrix), how to get a numpy array output which is equal to the original matrix multiplied by a scalar?

In [100]:
a = np.array(np.random.randint(0, 10, size=(2, 3)))
a

array([[8, 3, 7],
       [9, 9, 9]])

In [101]:
3 * a

array([[24,  9, 21],
       [27, 27, 27]])

### Exercise 9.

Create an identity matrix of dimension 4-by-4

In [105]:
np.eye((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Exercise 10.

Convert a 1-D array to a 3-D array

In [111]:
a = np.array(np.random.randint(0, 100, 27))

In [112]:
a.reshape(3, 3, 3)

array([[[28, 46, 33],
        [29, 55, 72],
        [17, 36, 77]],

       [[65, 76, 90],
        [40, 74, 11],
        [81, 52, 14]],

       [[14, 80, 28],
        [61, 40,  0],
        [91, 87, 65]]])

### Exercise 11.

Convert all the elements of a numpy array from float to integer datatype

In [131]:
a = np.array(10*np.random.random(10))
a

array([8.20089546, 7.61664306, 5.24865189, 9.38939031, 1.11283897,
       1.30278538, 8.6181384 , 0.6031732 , 9.62607767, 5.69232473])

In [145]:
a.astype('int')

array([1, 0, 0, 1, 1, 0, 1, 0, 0, 1])

### Exercise 12.

Convert a binary numpy array (containing only 0s and 1s) to a boolean numpy array

In [143]:
a = np.random.randint(0, 2, size=10)
a

array([1, 0, 0, 1, 1, 0, 1, 0, 0, 1])

In [144]:
a.astype('bool')

array([ True, False, False,  True,  True, False,  True, False, False,
        True])

### Exercise 13.

Stack 2 numpy arrays horizontally i.e., 2 arrays having the same 1st dimension (number of rows in 2D arrays)

In [149]:
a = np.random.randint(0, 100, size=(2, 5))
b = np.random.randint(0, 100, size=(2, 5))
a, b

(array([[88, 75, 24, 67, 34],
        [70, 22, 82, 69, 47]]),
 array([[33, 59, 38,  1, 48],
        [34, 58, 64, 69, 72]]))

In [151]:
np.hstack((a, b))

array([[88, 75, 24, 67, 34, 33, 59, 38,  1, 48],
       [70, 22, 82, 69, 47, 34, 58, 64, 69, 72]])

### Exercise 14.

Stack 2 numpy arrays vertically i.e., 2 arrays having the same last dimension (number of columns in 2D arrays)

In [152]:
a = np.random.randint(0, 100, size=(2, 5))
b = np.random.randint(0, 100, size=(2, 5))
a, b

(array([[73, 55, 61, 93, 12],
        [72,  3, 97, 36, 88]]),
 array([[24, 36,  0, 46, 85],
        [30, 94, 63, 60, 57]]))

In [158]:
np.vstack((a, b))

array([[73, 55, 61, 93, 12],
       [72,  3, 97, 36, 88],
       [24, 36,  0, 46, 85],
       [30, 94, 63, 60, 57]])

### Exercise 15.

Generate a sequence of numbers in the form of a numpy array from 0 to 100 with gaps of 2 numbers, for example: 0, 2, 4 ....

In [156]:
np.arange(0, 101, 2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

### Exercise 16.

From 2 numpy arrays, extract the indexes in which the elements in the 2 arrays match

In [185]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
b = np.array([1, 2, 4, 4, 0, 6, 1, 4, 1, 10])

In [186]:
np.where(a == b)

(array([0, 1, 3, 5, 9]),)

### Exercise 17.

Output a sequence of equally gapped 5 numbers in the range 0 to 100 (both inclusive)

In [190]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

### Exercise 18.

Output a matrix (numpy array) of dimension 2-by-3 with each and every value equal to 5

In [189]:
np.full((2, 3), 5)

array([[5, 5, 5],
       [5, 5, 5]])

### Exercise 19.

Take a two-dimensional array with random data and print the sorted array at the output

In [193]:
a = np.array(np.random.randint(0, 100, size=(2, 10)))
a

array([[64, 17, 95, 19, 85, 93, 99, 97, 64, 37],
       [62,  9, 30, 37, 48, 28, 81, 80, 89, 26]])

In [194]:
np.sort(a)

array([[17, 19, 37, 64, 64, 85, 93, 95, 97, 99],
       [ 9, 26, 28, 30, 37, 48, 62, 80, 81, 89]])

### Exercise 20.

Output an array by repeating a smaller array of 2 dimensions, 10 times

In [198]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [199]:
np.tile(a, 10)

array([[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1,
        2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6, 4, 5, 6, 4,
        5, 6, 4, 5, 6, 4, 5, 6]])

### Exercise 21.

Output a 5-by-5 array of random integers between 0 (inclusive) and 10 (exclusive)

In [200]:
np.random.randint(0, 10, size=(5, 5))

array([[5, 7, 1, 2, 4],
       [3, 0, 9, 0, 9],
       [5, 4, 5, 1, 3],
       [6, 4, 7, 0, 8],
       [3, 8, 9, 6, 5]])

### Exercise 22.

Output a 3-by-3 array of random numbers following normal distribution

In [203]:
np.random.normal(size=(3, 3))

array([[-1.61866255, -0.27699707, -0.83653769],
       [-0.324253  ,  0.31194097, -0.65386135],
       [ 0.71081347, -2.13834325, -0.63436713]])

### Exercise 23.

Given 2 numpy arrays as matrices, output the result of multiplying the 2 matrices (as a numpy array)

In [206]:
a = np.array(np.random.randint(0, 10, size=(3, 3)))
b = np.array(np.random.randint(0, 10, size=(3, 3)))
a, b

(array([[3, 9, 6],
        [4, 1, 9],
        [7, 2, 7]]),
 array([[0, 1, 9],
        [3, 2, 9],
        [4, 9, 8]]))

In [207]:
a @ b

array([[ 51,  75, 156],
       [ 39,  87, 117],
       [ 34,  74, 137]])

In [208]:
np.matmul(a, b)

array([[ 51,  75, 156],
       [ 39,  87, 117],
       [ 34,  74, 137]])

### Exercise 24.

Output the transpose of a matrix (as numpy array)

In [211]:
a = np.array(np.random.randint(0, 10, size=(3, 3)))
a

array([[3, 9, 5],
       [9, 9, 9],
       [1, 3, 9]])

In [213]:
a.T

array([[3, 9, 1],
       [9, 9, 3],
       [5, 9, 9]])

In [215]:
a.transpose()

array([[3, 9, 1],
       [9, 9, 3],
       [5, 9, 9]])

### Exercise 25.

Calculate the sine of an array of angles (in radians) using NumPy

In [216]:
import math

In [217]:
angles = np.array([math.pi, math.pi/2, 2 * math.pi])

In [219]:
np.sin(angles)

array([ 1.22464680e-16,  9.99999683e-01, -3.18530179e-03])

### Exercise 26.

Calculate the cosine similarity of 2 vectors (as numpy arrays)

In [220]:
np.cos(angles)

array([-1.00000000e+00,  7.96326711e-04,  9.99994927e-01])

### Exercise 27.

Output the array element indexes such that the array elements appear in the ascending order

In [221]:
a = np.array(np.random.randint(0, 10, size=10))
a

array([5, 2, 6, 5, 7, 7, 7, 9, 6, 6])

In [222]:
np.argsort(a)

array([1, 0, 3, 2, 9, 8, 4, 5, 6, 7])

### Exercise 28.

What is the output of the below code snippet?
```python
import numpy as np
arr = np.array([[4,2,0,5],[1,3,5,7]])
arr.size
```

In [225]:
import numpy as np

In [227]:
arr = np.array([[4,2,0,5],[1,3,5,7]])

In [228]:
arr.size

8

### Exercise 29.

we going to sort 3-D array `a`, but not in `axis=-1`.

**array a:**

In [254]:
from numpy.random import default_rng


rng = default_rng(seed=0)
a = rng.integers(1,10,size=(3,3,3))
a

array([[[8, 6, 5],
        [3, 3, 1],
        [1, 1, 2]],

       [[8, 6, 9],
        [5, 6, 9],
        [7, 6, 5]],

       [[6, 9, 3],
        [8, 7, 1],
        [4, 8, 5]]])

**when we sort array:**

In [255]:
np.sort(a)

array([[[5, 6, 8],
        [1, 3, 3],
        [1, 1, 2]],

       [[6, 8, 9],
        [5, 6, 9],
        [5, 6, 7]],

       [[3, 6, 9],
        [1, 7, 8],
        [4, 5, 8]]])

**But what we want:**
```python
array([[[1, 1, 1],
        [3, 3, 2],
        [8, 6, 5]],

       [[5, 6, 5],
        [7, 6, 9],
        [8, 6, 9]],

       [[4, 7, 1],
        [6, 8, 3],
        [8, 9, 5]]])
```

#### Solution:

In [252]:
np.sort(a, axis=1)

array([[[1, 1, 1],
        [3, 3, 2],
        [8, 6, 5]],

       [[5, 6, 5],
        [7, 6, 9],
        [8, 6, 9]],

       [[4, 7, 1],
        [6, 8, 3],
        [8, 9, 5]]])

### Exercise 30.

The heart rate of the patient was recorded in the x array on two consecutive days. Each row of this array represents the data recorded in one day.
We ask you to calculate the mean and standard deviation of each day using aggregation functions of Numpy.
```python
import numpy as np


x = np.array([[90, 87, 83, 100, 72, 67, 69, 73, 70],
              [80, 91, 111, 90, 62, 57, 59, 63, 60]])
```

#### Solution:

In [257]:
import numpy as np


x = np.array([[90, 87, 83, 100, 72, 67, 69, 73, 70],
              [80, 91, 111, 90, 62, 57, 59, 63, 60]])

In [266]:
np.array([np.mean(x, axis=-1), np.std(x, axis=-1)]).T

array([[79.        , 10.81151649],
       [74.77777778, 18.01097059]])

### Exercise 31.Reshape Manipulation

- Start with a random 3D array of shape (3, 4, 5)
- Reshape it to have shape (5, 4, 3) using .reshape()
- Verify that the total number of elements is unchanged

In [1]:
import numpy as np

orig_arr = np.random.rand(3, 4, 5)
print("Original Shape:", orig_arr.shape)

new_arr = orig_arr.reshape(5, 4, 3)
print("New Shape:", new_arr.shape)

assert orig_arr.size == new_arr.size

Original Shape: (3, 4, 5)
New Shape: (5, 4, 3)


### Exercise 32.Array Concatenation

- Generate two random integer arrays of shape (3, 4)
- Concatenate them vertically and horizontally
- Print the shapes of the concatenated arrays

In [ ]:
import numpy as np

arr1 = np.random.randint(0, 10, (3, 4))
arr2 = np.random.randint(0, 10, (3, 4))

vert_cat = np.vstack((arr1, arr2))
horz_cat = np.hstack((arr1, arr2))

print("Vertical Concat Shape:", vert_cat.shape)  
print("Horizontal Concat Shape:", horz_cat.shape)

### Exercise 33.Boolean Indexing

- Create an array of normally distributed random numbers
- Use boolean indexing to filter values within 2 standard deviations
- Print the percentage filtered

In [2]:
import numpy as np

arr = np.random.normal(size=1000)
filt = arr[(np.abs(arr) < 2*arr.std())]

print(len(filt)/len(arr) * 100, "% filtered")

95.39999999999999 % filtered


### Exercise 34.Aggregation

- Generate a random integer array of size 1000
- Use aggregation functions like sum, min, max, mean on array
- Time each operation to compare speeds

In [ ]:
import numpy as np
import time

arr = np.random.randint(0, 1000, 1000)

t1 = time.time()
arr.sum() 
t2 = time.time()
print("Sum time:", t2 - t1)

t1 = time.time()  
arr.min()
t2 = time.time()
print("Min time:", t2 - t1)



### Exercise 35.Memory Sharing

- Create a slice of an array and assign it to new variable
- Check if they share memory using `may_share_memory()`
- Repeat with indexing instead of slicing

In [3]:
import numpy as np

arr = np.random.rand(5, 5)
view = arr[:, 1:3]
print(np.may_share_memory(arr, view)) 

copy = arr[[0, 1], 1:3]  
print(np.may_share_memory(arr, copy))

True
False
